#!/usr/bin/env bash
set -euo pipefail

PDFCRYPT="./target/release/pdfcrypt"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

PASSED=0
FAILED=0

pass() { PASSED=$((PASSED + 1)); echo "  PASS: $1"; }
fail() { FAILED=$((FAILED + 1)); echo "  FAIL: $1 — $2"; }

check() {
    local name="$1"; shift
    if "$@" >/dev/null 2>&1; then
        pass "$name"
    else
        fail "$name" "exit code $?"
    fi
}

check_fail() {
    local name="$1"; shift
    if "$@" >/dev/null 2>&1; then
        fail "$name" "expected failure but succeeded"
    else
        pass "$name"
    fi
}

# ── Build ────────────────────────────────────────────────────────
echo "Building pdfcrypt..."
cargo build --bin pdfcrypt --release 2>&1 | tail -1

# ── Generate test PDFs with various Linux tools ──────────────────

echo ""
echo "=== Generating test PDFs ==="

# 1) Ghostscript — minimal PostScript to PDF
echo "%!PS
/Helvetica findfont 24 scalefont setfont
72 700 moveto (Generated by Ghostscript) show
showpage" > "$TMP/gs_input.ps"
gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile="$TMP/from_gs.pdf" "$TMP/gs_input.ps"
echo "  from_gs.pdf        (Ghostscript)     $(wc -c < "$TMP/from_gs.pdf") bytes"

# 2) ps2pdf — PostScript to PDF via ps2pdf wrapper
echo "%!PS
/Courier findfont 18 scalefont setfont
72 700 moveto (Generated by ps2pdf) show
showpage" > "$TMP/ps2pdf_input.ps"
ps2pdf "$TMP/ps2pdf_input.ps" "$TMP/from_ps2pdf.pdf"
echo "  from_ps2pdf.pdf    (ps2pdf)          $(wc -c < "$TMP/from_ps2pdf.pdf") bytes"

# 3) ImageMagick convert — image to PDF
convert -size 400x200 xc:white -font Helvetica -pointsize 28 \
    -annotate +50+100 "Generated by ImageMagick" "$TMP/from_imagemagick.pdf"
echo "  from_imagemagick.pdf (ImageMagick)   $(wc -c < "$TMP/from_imagemagick.pdf") bytes"

# 4) qpdf — create a minimal PDF then linearize it
qpdf --empty --pages "$TMP/from_gs.pdf" -- "$TMP/from_qpdf.pdf"
echo "  from_qpdf.pdf      (qpdf)            $(wc -c < "$TMP/from_qpdf.pdf") bytes"

# 5) pdftk — merge two PDFs into one multi-page PDF
pdftk "$TMP/from_gs.pdf" "$TMP/from_ps2pdf.pdf" cat output "$TMP/from_pdftk.pdf"
echo "  from_pdftk.pdf     (pdftk, 2 pages)  $(wc -c < "$TMP/from_pdftk.pdf") bytes"

# 6) mutool — convert/clean a PDF
mutool clean "$TMP/from_gs.pdf" "$TMP/from_mutool.pdf"
echo "  from_mutool.pdf    (mutool clean)    $(wc -c < "$TMP/from_mutool.pdf") bytes"

# 7) LibreOffice — text file to PDF
echo "Generated by LibreOffice" > "$TMP/lo_input.txt"
libreoffice --headless --convert-to pdf --outdir "$TMP" "$TMP/lo_input.txt" >/dev/null 2>&1
mv "$TMP/lo_input.pdf" "$TMP/from_libreoffice.pdf"
echo "  from_libreoffice.pdf (LibreOffice)   $(wc -c < "$TMP/from_libreoffice.pdf") bytes"

PDFS=(from_gs from_ps2pdf from_imagemagick from_qpdf from_pdftk from_mutool from_libreoffice)

# ── Test A: Lock each PDF, verify with qpdf and pdfinfo ─────────

echo ""
echo "=== Test A: Lock each PDF (same user/owner pw), verify externally ==="
for name in "${PDFS[@]}"; do
    src="$TMP/${name}.pdf"
    dst="$TMP/${name}_locked.pdf"
    dec="$TMP/${name}_qpdf_dec.pdf"

    if $PDFCRYPT lock "$src" "$dst" --user-password test123 2>/dev/null; then
        pass "lock $name"
    else
        fail "lock $name" "pdfcrypt lock failed"; continue
    fi

    check "qpdf verify $name"   qpdf --password=test123 --decrypt "$dst" "$dec"
    check "pdfinfo verify $name" pdfinfo -upw test123 "$dst"
done

# ── Test B: Lock with different user/owner, verify both work ─────

echo ""
echo "=== Test B: Lock with user='open' owner='master', verify both ==="
for name in "${PDFS[@]}"; do
    src="$TMP/${name}.pdf"
    dst="$TMP/${name}_dual.pdf"

    $PDFCRYPT lock "$src" "$dst" --user-password open --owner-password master 2>/dev/null

    check "qpdf user pw $name"  qpdf --password=open   --decrypt "$dst" "$TMP/${name}_dual_u.pdf"
    check "qpdf owner pw $name" qpdf --password=master --decrypt "$dst" "$TMP/${name}_dual_o.pdf"
    check_fail "qpdf wrong pw $name" qpdf --password=wrong --decrypt "$dst" "$TMP/${name}_dual_w.pdf"
done

# ── Test C: Unlock with pdfcrypt (user pw and owner pw) ──────────

echo ""
echo "=== Test C: Round-trip lock+unlock with pdfcrypt ==="
for name in "${PDFS[@]}"; do
    src="$TMP/${name}.pdf"
    locked="$TMP/${name}_rt.pdf"

    $PDFCRYPT lock "$src" "$locked" --user-password abc --owner-password xyz 2>/dev/null

    check "unlock user pw $name"  $PDFCRYPT unlock "$locked" "$TMP/${name}_rt_u.pdf" --password abc
    check "unlock owner pw $name" $PDFCRYPT unlock "$locked" "$TMP/${name}_rt_o.pdf" --password xyz
    check_fail "unlock wrong pw $name" $PDFCRYPT unlock "$locked" "$TMP/${name}_rt_w.pdf" --password nope
done

# ── Test D: Unlock qpdf-encrypted PDFs with pdfcrypt ─────────────

echo ""
echo "=== Test D: Decrypt qpdf-encrypted PDFs with pdfcrypt ==="
for name in "${PDFS[@]}"; do
    src="$TMP/${name}.pdf"
    qenc="$TMP/${name}_qenc.pdf"
    qdec="$TMP/${name}_qdec.pdf"

    qpdf "$src" "$qenc" --allow-weak-crypto --encrypt userqp ownerqp 128 --
    check "pdfcrypt unlocks qpdf-encrypted $name (user pw)" \
        $PDFCRYPT unlock "$qenc" "$qdec" --password userqp
    check "pdfcrypt unlocks qpdf-encrypted $name (owner pw)" \
        $PDFCRYPT unlock "$qenc" "${qdec}_o" --password ownerqp
done

# ── Test E: Lock with pdfcrypt, decrypt with pdftk and mutool ────

echo ""
echo "=== Test E: Cross-tool decrypt (pdftk, mutool) ==="
for name in "${PDFS[@]}"; do
    locked="$TMP/${name}_locked.pdf"  # from Test A, pw=test123

    if pdftk "$locked" input_pw test123 output "$TMP/${name}_pdftk_dec.pdf" 2>/dev/null; then
        pass "pdftk decrypt $name"
    else
        fail "pdftk decrypt $name" "pdftk failed"
    fi

    if mutool clean -p test123 "$locked" "$TMP/${name}_mutool_dec.pdf" 2>/dev/null; then
        pass "mutool decrypt $name"
    else
        fail "mutool decrypt $name" "mutool failed"
    fi
done

# ── Test F: Edge cases ───────────────────────────────────────────

echo ""
echo "=== Test F: Edge cases ==="

check_fail "lock already-encrypted PDF" \
    $PDFCRYPT lock "$TMP/from_gs_locked.pdf" "$TMP/double.pdf" --user-password x

check_fail "unlock non-encrypted PDF" \
    $PDFCRYPT unlock "$TMP/from_gs.pdf" "$TMP/nope.pdf" --password x

check "empty user pw, owner-only" \
    $PDFCRYPT lock "$TMP/from_gs.pdf" "$TMP/empty_user.pdf" --user-password "" --owner-password secret

check "qpdf with empty user pw" \
    qpdf --password="" --decrypt "$TMP/empty_user.pdf" "$TMP/empty_user_dec.pdf"

check "qpdf with owner pw on empty-user PDF" \
    qpdf --password=secret --decrypt "$TMP/empty_user.pdf" "$TMP/empty_user_dec2.pdf"

# ── Summary ──────────────────────────────────────────────────────

echo ""
echo "========================================"
echo "  $PASSED passed, $FAILED failed"
echo "========================================"
if [ "$FAILED" -eq 0 ]; then
    echo "  ALL TESTS PASSED"
else
    exit 1
fi
